### ISSUE TITLE
make-sub-table fails when parent table doesn't have column-names and column-types

### ISSUE THREAD

**Issue by bmansurov** [AccelerationNet/data-table#5]
Hi, the following snippet of code fails:

```
(data-table:make-sub-table
 (make-instance 'data-table:data-table
                :rows '((1 a)
                        (2 b))))
```

But the following doesn't:
```
(data-table:make-sub-table
 (make-instance 'data-table:data-table
                :column-names '(count item)
                :column-types '(integer symbol)
                :rows '((1 a)
                        (2 b))))
```
Should `column-names` and `column-types` be required arguments to `make-instance`? Or should `make-sub-table` check for their validity? Or something else? I'm happy to submit a patch.

**Comment by bobbysmith007** [comment]
I have not gotten to program Common Lisp in quite a while.  I am open to any reasonable bug fix.  Generally all datatables I used had column names.

To me it seems like https://github.com/AccelerationNet/data-table/blob/master/data-table.lisp#L182
could be changed to allow nil / too-short-lists as follows: 

```
(flet ((subs (l) 
     (loop for item in l
              for idx from 0
              if (and (>= idx lci) (< idx uci))
              collect item))
      ))
...
``` 

This wont throw errors regardless of whether or not the indexes are specified badly for the input data.   Please write a test around this if you work it into a patch.  

Thanks!
Cheers,
Russ Tyndall

**Comment by bmansurov** [comment]
OK, thank you. I'll try to submit a patch over the weekend.

**Comment by bobbysmith007** [comment]
Thank you for the patch
